name: Go get tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
# dgit started breaking with go get tests after 1.15, so
# we only run 1.11 (the oldest that we support) and 1.15
            go: ['1.11', '1.15']

    steps:

    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build dgit
      run: go build

    - name: Run tests for go get command
      run: ./go-get-tests.sh



